block/022: allow to run with built-in null_blk driver
The test case block/022 sets the null_blk parameter shared_tags=1 for
testing. The parameter has been set as a module parameter, so the
null_blk driver must be loadable. However, null_blk allows you to set
shared_tags as a configfs parameter since the kernel commit XXXXXXXXXXXX
("null_blk: add configfs variable shared_tags"). The test case can now
be run with the built-in null_blk driver by specifying shared_tags
through configfs.

Modify the test case for that purpose. Refer to the null_blk feature
list and check if shared_tags can be specified through configfs. If so,
specify the parameter through configfs. If not, check in requires() that
shared_tags can be specified as a module parameter. Then call
_init_null_blk() in test() and specify shared_tags=1 at null_blk module
load.

Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>

diff --git a/tests/block/022 b/tests/block/022
--- a/tests/block/022
+++ b/tests/block/022
@@ -12,8 +12,11 @@ DESCRIPTION="Test hang caused by freeze/unfreeze sequence"
 TIMED=1
 
 requires() {
-	_have_null_blk && _have_module_param null_blk shared_tags
+	_have_null_blk
 	_require_min_cpus 2
+	if ! _have_null_blk_feature shared_tags; then
+		_have_module_param null_blk shared_tags
+	fi
 }
 
 hotplug_test() {
@@ -28,12 +31,24 @@ test() {
 	echo "Running ${TEST_NAME}"
 	: "${TIMEOUT:=30}"
 
-	if ! _init_null_blk shared_tags=1 nr_devices=0; then
-		return 1
+	local configfs_has_shared_tags=True
+
+	# Old kernels do not have the shared_tags attribute in configfs. In that
+	# case, call _init_null_blk() to set shared_tags as a module parameter.
+	if ! _have_null_blk_feature shared_tags; then
+		configfs_has_shared_tags=False
+		if ! _init_null_blk shared_tags=1 nr_devices=0; then
+			echo "Loading null_blk failed"
+			return 1
+		fi
 	fi
 
 	mkdir -p /sys/kernel/config/nullb/0
 	mkdir -p /sys/kernel/config/nullb/1
+	if [[ $configfs_has_shared_tags == True ]]; then
+		echo 1 > /sys/kernel/config/nullb/0/shared_tags
+		echo 1 > /sys/kernel/config/nullb/1/shared_tags
+	fi
 	hotplug_test 0 &
 	pid0=$!
 	hotplug_test 1 &
