common/nvme: retry nvme connect on failure with EINTR for tcp transport
The test case nvme/018 sometimes fail for tcp transport due to the "nvme
connect" command failure in _nvme_connect_subsys(). This failure can be
recreated by repeating the test case hundreds of times. On failure, nvme
tcp host driver reports " failed to receive icresp, error -4", which
indicates EINTR.

This failure can be recovered by trying the nvme connect again. To avoid
the failure, check if the ENITR happened on failure. If so, do the "nvme
connect" command again.

Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>

diff --git a/common/nvme b/common/nvme
--- a/common/nvme
+++ b/common/nvme
@@ -279,7 +279,7 @@ _nvme_connect_subsys() {
 	local tls=false
 	local concat=false
 	local port
-	local i
+	local i ret
 	local -a ARGS
 
 	while [[ $# -gt 0 ]]; do
@@ -417,6 +417,20 @@ _nvme_connect_subsys() {
 	fi
 	ARGS+=(-o json)
 	connect=$(nvme connect "${ARGS[@]}" 2> /dev/null)
+	ret=$?
+	if ((ret)); then
+		echo "nvme connect command failed: ARGS: ${ARGS[@]}" >> "$FULL"
+		if [[ "$nvme_trtype" == tcp ]]; then
+			if _dmesg_since_test_start | tail -2 | grep --quiet \
+				"failed to receive icresp, error -4"; then
+				sleep 1
+				echo "TCP nvme connect failed due to INTR. Try again." >> "$FULL"
+				connect=$(nvme connect "${ARGS[@]}" 2> /dev/null)
+				ret=$?
+			fi
+		fi
+		((ret)) && return 1
+	fi
 
 	# Wait until device file and sysfs attributes get ready
 	if [[ ${no_wait} = false ]]; then
